DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS assigned CASCADE;

DROP TYPE IF EXISTS USER_ROLE;
DROP TYPE IF EXISTS TICKET_STATUS;
DROP TYPE IF EXISTS ISSUE_TYPE;
